### ISSUE TITLE
querySelector will get any descendant, not only direct children

### ISSUE THREAD

**Issue by pbb72** [Luuka/gpx-parser#6]
In the function "getElementValue", you use a querySelector to get a child element value. (For example, `track.name = keepThis.getElementValue(trk, "name");`) However, querySelector finds any descendants, not only direct children. If the element itself doesn't have the sought after element, but a lower descendent does (in our example, this could be a trackpoint), then this value is returned.

https://github.com/Luuka/gpx-parser/blob/46193290e85328be89c28e9d142925452ca84ebd/src/gpx-parser.js#L127

**Comment by pbb72** [comment]
Sorry, strike that issue. I had changed it in my own copy of your code, and removed the ":scope". And then I blamed you. :sob:

**Comment by Luuka** [comment]
@pbb72 Thanks for your report and don't worry about the false alarm. I hope my code fit your needs ;)

**Comment by pbb72** [comment]
I might submit a pull request someday with fixes for making the code compatible with more browsers. `:scope` for example is apparently not supported by Internet Explorer... 😄
